backend:
#  name: test-repo
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
summary: "Version: {{version}} - {{title}}"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Description", name: "body", widget: "string", required: false}
      - label: 'Items'
        name: "items"
        widget: list
        fields:
          - { label: "ID", name: "id", widget: "string"}
          - { label: "Comments", name: "description", widget: "string", required: false}
          - label: 'Translations'
            name: "translation"
            widget: list
            fields:
              - { label: "Language code", name: "code", widget: "string"}
              - { label: "Language name", name: "name", widget: "string"}
              - { label: "Translated value", name: "value", widget: "string", required: false}
  - name: "faqs"
    label: "FAQs"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - label: 'Questions'
        name: "questions"
        widget: list
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Custom Slug", name: "slug", widget: "string"}
          - { label: "Color", name: "color", widget: "string"}
          - { label: "Icon", name: "icon", widget: "string"}
          - label: 'Answers'
            name: "answers"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Custom ID", name: "id", widget: "string"}
              - { label: "Publish Date", name: "date", widget: "datetime" }
              - { label: "Answer", name: "answer", widget: "markdown"}
